name: Node.js CI

on:
  branches:
    - main
run-name: release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
      - run: npm ci
      - run: npm run-script lib:build:prod
      - run: npm run-script build
      - run: npm run-script test
      - run: cd dist/ngx-snotifire && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
